const List<String> QuoteTopics = [
  'A book is like a garden carried in your pocket (Chinese Proverb)',
  'A soul arms itself by prayer for all kinds of combat (St. Faustina Kowalska)',
  'All sorrows are less with bread (Don Quixote)',
  "Doing nothing is the most tiresome job because you can't quit and rest (Confucius)",
  'Doubt makes the mountain which faith can move (Proverb)',
  'Gods love for us is not greater in heaven than it is now (St. Thomas Aquinas)',
  'Ice cream is happiness condensed. (Jesse L. Adams)',
  'If you do not hope, you will not find what is beyond your hope',
  'In a true tragedy, both parties must be right (George W. Hegel)',
  'Love is infinitely inventive (St. Vincent de Paul)',
  'The reformer is generally wrong about what is right (G.K. Chesterton)',
  'The world is indeed comic, but the joke is on mankind. (H.P. Lovecraft)',
  'Total abstinence is easier than perfect moderation (St. Augustine)',
  'What you are in love with, what siezes your imagination, will affect everything (P. Arrupe S.J.)',
  'Worries go down better with soup than without (Jewish Proverb)',
  "You can't be brave if you have had only wonderful things happen to you. (Mary T. Moore)",
  'Arbitrary power is most easily established on the ruins of liberty abused to licentiousness (George Washington)',
  "Can art change the world?  Maybe we should change the question: Can art change people's lives?",
  "Certain shades of limelight wrecks a girl's complexion (Truman Capote)",
  "Dude, suckin' at somethin' is the first step towards bein' sorta good at somethin' (Jake the Dog)",
  'Excellence is the best deterrent to racism or sexism (Oprah Winfrey)',
  'Failure is the condiment that gives success its flavor (Truman Capote)',
  'For many, the American dream has become a nightmare (Bernie Sanders)',
  'I believe that, as long as there is plenty, poverty is evil (Robert Kennedy)',
  "I'm the only one that has to die when it's time for me to die, so let me live my life, the way I want to (Jimi Hendrix)",
  "If your ship doesn't come in, swim out to meet it (Jonathan Winters)",
  'It is a wise man who said that there is no greater inequality than the equal treatment of unequals (Justice Felix Frankfurter)',
  "It's a scientific fact that if you stay in California you lose one point of your IQ every year (Truman Capote)",
  "Loneliness and the feeling of being unwanted is the most terrible poverty (Mother Teresa)",
  "Nature chooses who will be transgender; individuals don't choose this (Mercedes Ruehl)",
  "Patience has its limits.  Take it too far and it is cowardice (George Jackson)",
  "Privacy is not an option, and it shouldn't be the price we accept for just getting on the Internet (Gary Kovacs)",
  "Rejection is an opportunity for your selection (Bernard Branson)",
  "Smart women love smart men more than smart men love smart women (Natalie Portman)",
  "Sometimes by losing a battle you find a new way to win the war (Donald Trump)",
  "Success is how high you bounce when you hit the bottom (General George Patton)",
  "Sweetie, if you're going to be two-faced, at least make one of them pretty (Marilyn Monroe)",
  "The American Negro can never be blamed for his racial animosities -- he is only reacting to 400 years of the conscious racism of the American whites (Malcolm X)",
  "The media is the most powerful entity on earth.  They have the power to make the innocent guilty and to make the guilty innocent, and that's power, because they control the mids of the masses (Malcom X)",
  "The world is a dangerous place to live; not because of the people who are evil, but because of the people who never do anything about it (Albert Einstein)",
  "We must stop thinking of the individual and start thinking about what is best for society (Hillary Clinton)",
  "Wise men speak because they have something to say, fools because they have to say something (Plato)",
  "Words have meaning.  And, their meaning doesn't change (Justice Antonin Scalia)",
  "You will not be punished for your anger.  You will be punished by your anger (Buddha)",
  "Deliver me from writers who say the way they live doesn't matter (Alice Walker)",
  "Denouncing evil is a far cry from doing good (Philip Gourevitch)",
  "Drawing on my fine command of the English language, I said nothing (Robert Benchley)",
  "Everything is theoretically impossible, until it is done (Robert A. Heinlein)",
  "Housework can't kill you, but why take a chance? (Phyllis Diller)",
  "If I have seen further than others, it is by standing upon the shoulders of giants (Isaac Newton)",
  "If my life wasn't funny, it would just be true, and that's unacceptable (Carrie Fisher)",
  "It would be possible to describe everything scientifically, but it would make no sense; it would be without meaning, as if you described a Beethoven symphony as a variation of wave pressure (Albert Einstein)",
  "Our problems stem from our acceptance of this filthy, rotten system (Dorothy Day)",
  "Science never solves a problem without creating ten more (George Bernard Shaw)",
  "The science of operations, as derived from mathematics more especially, is a science of itself, and has its own abstract truth and value (Ada Lovelace)",
  "There's no crying in baseball (A League of Their Own)",
  "Where we're going, we don't need roads (Back to the Future)",
  "An unexamined life is not worth living (Socrates)",
  "But man is not made for defeat.  A man can be destroyed but not defeated (Ernest Hemingway)",
  "Challenges are what make life interesting and overcoming them is what makes  life meaningful (Joshua J. Marine)",
  "Do or do not, there is no try (Yoda)",
  "Education is the most powerful weapon which you can use to change the world (Nelson Mandela)",
  "Every moment of light and dark is a miracle (Walt Whitman)",
  "If opportunity doesn't knock, build a door (Milton Berle)",
  "Independance is happiness (Susan B. Anthony)",
  "Learning never exhausts the mind (Leonardi da Vinci)",
  "Life isn't about finding yourself.  Life is about creating yourself (George Bernard Shaw)",
  "Life's most persistent and urgent question is, 'What are you doing for others?' (Martin Luther King, Jr.)",
  "Not all those who wander are lost (J. R. R. Tolkein)",
  "Once you learn to read you will be forever free (Frederick Douglas)",
  "Tell me and I forget.  Teach me and I remember. Involve me and I learn (Benjamin Franklin)",
  "The best preparation for tomorrow is doing your best today (H. Jackson Brown, Jr.)",
  "The only journey is the one within (Rainer Maria Rilke)",
  "There is only one corner of the universe you can be certain of improving, and that's your own self (Aldous Huxley)",
  "What we think, we become (Buddha)",
  "With great power comes great responsibility (Spiderman)",
  "Everything you can imagine is real (Pablo Picasso)",
  "My thoughts are stars I cannot fathom into constellations (John Green)",
  "Sometimes the questions are complicated and the answers are simple (Dr. Seuss)",
  "We don't see things as they are, we see things as we are (Anais Nin)",
  "A hasty man drinks his tea with a fork (Chinese Proverb)",
  "Action is often the best course of action (Glenn Beck)",
  "Angels fly because they take themselves lightly (G. K. Chesterton)",
  "Be wise as serpents and innocent as doves (Matthew 10:16)",
  "Beauty without expression tires (Ralph Waldo Emerson)",
  "Darkness is only driven out with light, not more darkness (Martin Luther King Jr.)",
  "Focus on where you want to go, not on what you fear (Anthony Robbins)",
  "From wonder into existence opens (Lao Tzu)",
  "I am a part of everything I have read (John Kieran)",
  "Joy is often a net of love by which you can catch souls (Mother Teresa)",
  "Let justice be done through the word perish (St. Augustine)",
  "Man's most valuable trait is a judicial sense of what not to beleive (Europides)",
  "Music is an outburst of the soul (Frederick Delius)",
  "Not all who wander are lost (J. R. R.  Tolkein)",
  "Our peril is not attack, it is decay (G. K. Chesterton)",
  "Teachers open the door, but you must enter by yourself (Chinese Proverb)",
  "The cause of America is the cause of mankind (Thomas Paine)",
  "The difference between greatness and mediocrity is how a person views a mistake (Nelson Boswell)",
  "The person who says it can't be done should not interrupt the person doing it (Chinese Proverb)",
  "Things are only impossible until they're not (Jean Luc Picard)"
      "We are alike more than we are unlike (Maya Angelou)",
  "We can only learn to love by loving (Iris Murdoch)",
  "When people are bored, it is primarily with their own selves (Eric Hoffer)",
  "Words, like eyeglasses, blur eveything they do not make clear (Joseph Joubert)",
  "Any act of kindness, no matter how small, is ever wasted (Aesop)",
  "The only thing permanent is change (Heraclitus)",
  "You cannot shake hands with a clenched fist (Gandhi)",
  "A room without books is like a body without a soul (Marcus Tullius Cicero)",
  "Be yourself; everyone else is already taken (Oscar Wilde)",
  "Blessed are the forgetful, for they get the better even of their blunders (Friedrich Nietzsche)",
  "Darkness cannot drive out darkness: only light can do that.  Hate cannot drive out hate: only love can do that (Martin Luther King Jr.)",
  "Don't cry because it's over, smile because it happened (Dr. Seuss)",
  "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten (Neil Gaimon)",
  "If you tell the truth, you don't have to remember anything (Mark Twain)",
  "In individuals, insanity is rare, but in groups, parties, nations, and epochs, it is the rule (Friedrich Nietzsche)",
  "In three words I can sum up everything I've learned about life: it goes on (Robert Frost)",
  "It is our choices, Harry, that show what we truly are, far more than our abilities (J. K. Rowling)",
  "Maybe the target nowadays is not to discover what we are but to refuse what we are (Michel Foucault)",
  "No act of kindness, no matter how small, is ever wasted (Aesop)",
  "The fool doth think he is wise, but the wise man knows himself to be a fool (William Shakespearre)",
  "The truth is, everyone is going to hurt you.  You just got to find the ones worth suffering for (Bob Marley)",
  "To live is the rarest thing in the world.  Most people exist, that is all (Oscar Wilde)",
  "Truth uncompromisingly told will always have its ragged edges (Herman Melville)",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe (Albert Einstein)",
  "You only live one, but if you do it right, once is enough (Mae West)",
  "Earthly knowledge is but shadow (Plato)",
  "I find your lack of faith disturbing (Darth Vader)",
  "Never be limited by other people's limited imaginations Dr. Mae Jemison)",
  "No human being is illegal (Elie Wiesel)",
  "No man really knows about other human beings.  The besthe can do is to suppose that they are like himself (John Steinbeck)",
  "No one is as capable of gratitude as one who has emerged from the kingdom of night (Elie Wiesel)",
  "People are trapped in history and history is trapped in them (James Baldwin)",
  "Reason lives in language (Emmanuel Levinas)",
  "Self-control is the cheif element in self-respect, and self-respect is the cheif element in courage (Thucydides)",
  "The end justifies the meas (Niccolo Machiavelli)",
  "The greatest glory in living lies not in never falling, but in rising every time we fall (Nelson Mandela)",
  "The only person you should try to be better than is the person you were yesterday (Anonymous)",
  "The proper function of man is to live, not to exist.  I shall not waste my days in trying to prolong them.  I shall use my time (Jack London)",
  "The time is always right to do what is right (Dr. Martin Luther King, Jr.)",
  "What is right to be done cannot be done too soon (Jane Austen)",
  "Blessed are the hearts that can bend; they shall never be broken. (Albert Camus)",
  "In three words I can sum up everything I've learned about life: it goes on. (Robert Frost)",
  "The supreme art of war is to subdue the enemy without fighting. (Sun Tzu)",
  "A leader is one who knows the way, goes the way, and shows the way. (John C. Maxwell)",
  "The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do. You can act to change and control your life; and the procedure, the process is its own reward. (Amelia Earhart)",
  "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. (Marcus Aurelius)",
  "But man is not made for defeat. A man can be destroyed but not defeated. (Ernest Hemingway)",
  "All that we see or seem is but a dream within a dream. (Edgar Allan Poe)",
  "Love has no age, no limit; and no death. (John Galsworthy)",
  "Happiness can exist only in acceptance. (George Orwell)",
  "Where there is love there is life. (Mahatma Gandhi)",
  "There is nothing permanent except change. (Heraclitus)",
  "Always remember that you are absolutely unique. Just like everyone else. (Margaret Mead)",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. (Ralph Waldo Emerson)",
  "Life is not a problem to be solved, but a reality to be experienced. (Soren Kierkegaard)",
  "You don't choose your family. They are God's gift to you, as you are to them. (Desmond Tutu)",
  "I have not failed. I've just found 10,000 ways that won't work. (Thomas A. Edison)",
  "When you reach the end of your rope, tie a knot in it and hang on. (Franklin D. Roosevelt)",
  "Today you are you! That is truer than true! There is no one alive who is you-er than you! (Dr. Seuss)",
  "Lord, make me an instrument of thy peace. Where there is hatred, let me sow love. (Francis of Assisi)",
  "Love is composed of a single soul inhabiting two bodies. (Aristotle)",
  "Honesty is the first chapter in the book of wisdom. (Thomas Jefferson)",
  "Let us sacrifice our today so that our children can have a better tomorrow. (A. P. J. Abdul Kalam)",
  "Learning never exhausts the mind. (Leonardo da Vinci)",
  "If opportunity doesn't knock, build a door. (Milton Berle)",
  "The journey of a thousand miles begins with one step. (Lao Tzu)",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. (Winston Churchill)",
  "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. (Swami Vivekananda)",
  "The secret of getting ahead is getting started. (Mark Twain)",
  "There is no charm equal to tenderness of heart. (Jane Austen)",
  "You cannot shake hands with a clenched fist. (Indira Gandhi)",
  "Independence is happiness. (Susan B. Anthony)",
  "Love isn't something you find. Love is something that finds you. (Loretta Young)",
  "Friends show their love in times of trouble, not in happiness. (Euripides)",
  "Keep your face always toward the sunshine - and shadows will fall behind you. (Walt Whitman)",
  "I love you the more in that I believe you had liked me for my own sake and for nothing else. (John Keats)",
  "Change your thoughts and you change your world. (Norman Vincent Peale)",
  "You can't blame gravity for falling in love. (Albert Einstein)",
  "Do all things with love. (Og Mandino)",
  "Education is the most powerful weapon which you can use to change the world. (Nelson Mandela)",
  "Wise men speak because they have something to say; Fools because they have to say something. (Plato)",
  "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak. (Thomas Carlyle)",
  "Let us be grateful to people who make us happy, they are the charming gardeners who make our souls blossom. (Marcel Proust)",
  "There is only one corner of the universe you can be certain of improving, and that's your own self. (Aldous Huxley)",
  "The World is my country, all mankind are my brethren, and to do good is my religion. (Thomas Paine)",
  "Do not mind anything that anyone tells you about anyone else. Judge everyone and everything for yourself. (Henry James)",
  "There is nothing on this earth more to be prized than true friendship. (Thomas Aquinas)",
  "A single rose can be my garden... a single friend, my world. (Leo Buscaglia)",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn. (Benjamin Franklin)",
  "If you cannot do great things, do small things in a great way. (Napoleon Hill)",
  "Whoever is happy will make others happy too. (Anne Frank)",
  "If you can’t beat ’em, join ’em (Chinese Proverb)",
  "The grass is always greener on the other side (Chinese Proverb)",
  "Good things come to those who wait (Chinese Proverb)",
  "The squeaky wheel gets the grease (Chinese Proverb)",
  "Don’t put off until tomorrow what you can do today (Chinese Proverb)",
  "You can lead a horse to water, but you can’t make her drink it (Chinese Proverb)",
  "A picture is worth a thousand words (Chinese Proverb)",
  "Birds of a feather flock together (Chinese Proverb)",
  "A journey of a thousand miles begins with a single step (Chinese Proverb)",
  "Don’t put all of your eggs in one basket (Chinese Proverb)",
  "Don’t judge a book by its cover (Chinese Proverb)",
  "You can’t always get what you want (Chinese Proverb)",
  "Don’t bite the hand that feeds you (Chinese Proverb)",
  "Easy come, easy go (Chinese Proverb)",
  "Actions speak louder than words. (Chinese Proverb)",
  "Beauty is in the eye of the beholder (Chinese Proverb)",
  "No man is an island (Chinese Proverb)",
  "Fortune favors the bold (Chinese Proverb)",
  "The early bird gets the worm (Chinese Proverb)",
  "Practice makes perfect (Chinese Proverb)",
  "The enemy of my enemy is my friend (Chinese Proverb)",
  "God helps those who help themselves (Chinese Proverb)",
  "Like father, like son (Chinese Proverb)",
  "Two wrongs don’t make a right (Chinese Proverb)",
  "If you want something done right, you have to do it yourself (Chinese Proverb)",
  "Time is money (Chinese Proverb)",
  "Two heads are better than one (Chinese Proverb)",
  "Hope for the best, prepare for the worst (Chinese Proverb)",
  "There is no time like the present (Chinese Proverb)",
  "Keep your friends close, and your enemies closer (Chinese Proverb)",
  "Better late than never (Chinese Proverb)",
  "A watched pot never boils (Chinese Proverb)",
  "If you play with fire, you’ll get burned (Chinese Proverb)",
];